### ISSUE TITLE
10-041: not compatible with python2.7

### ISSUE THREAD

**Issue by AdfinisTaco** [adfinis/ansible-collection-maintenance#80]
## Issue

When running the maintenance playbook on (older) systems that default to python2.7, the following error is thrown:

```
TASK [adfinis.maintenance.maintenance_10_linux : 10-041: Security: Logins: Are there logins from suspicious hosts/users? | Gather past logins from `last` output] ************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ipaddress.AddressValueError: '0.0.0.0' does not appear to be an IPv4 or IPv6 network. Did you pass in a bytes (str in Python 2) instead of a unicode object?
fatal: [vm-***-*******-01.*****.**.**]: FAILED! => {
    "changed": false,
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDOUT:

Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1731019100.788824-3893418-265577600876890/AnsiballZ_lastlogins.py", line 107, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1731019100.788824-3893418-265577600876890/AnsiballZ_lastlogins.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1731019100.788824-3893418-265577600876890/AnsiballZ_lastlogins.py", line 48, in invoke_module
    run_name='__main__', alter_sys=True)
  File "/usr/lib64/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_adfinis.maintenance.lastlogins_payload_bpTdWW/ansible_adfinis.maintenance.lastlogins_payload.zip/ansible_collections/adfinis/maintenance/plugins/modules/lastlogins.py", line 221, in <module>
  File "/tmp/ansible_adfinis.maintenance.lastlogins_payload_bpTdWW/ansible_adfinis.maintenance.lastlogins_payload.zip/ansible_collections/adfinis/maintenance/plugins/modules/lastlogins.py", line 217, in main
  File "/tmp/ansible_adfinis.maintenance.lastlogins_payload_bpTdWW/ansible_adfinis.maintenance.lastlogins_payload.zip/ansible_collections/adfinis/maintenance/plugins/modules/lastlogins.py", line 188, in run_module
  File "/tmp/ansible_adfinis.maintenance.lastlogins_payload_bpTdWW/ansible_adfinis.maintenance.lastlogins_payload.zip/ansible_collections/adfinis/maintenance/plugins/modules/lastlogins.py", line 188, in <genexpr>
  File "/usr/lib/python2.7/site-packages/ipaddress.py", line 199, in ip_network
    ' a unicode object?' % address)
ipaddress.AddressValueError: '0.0.0.0' does not appear to be an IPv4 or IPv6 network. Did you pass in a bytes (str in Python 2) instead of a unicode object?



MODULE_STDERR:

Shared connection to 172.**.**.** closed.
```

## Suggested solution

Enforce python3. if there is no python3 available on the system then issue a warning in the output and skip this task

## Workaround

Add `-e 'ansible_python_interpreter=/usr/bin/python3'` to the ansible command.

**Comment by s3lph** [comment]
Hi @AdfinisTaco

I don't think there is a way to enforce using Python 3 on a plugin level. The plugins are executed with whatever Ansible thinks is the best Python interpreter. So your proposed "workaround" actually is the "proper" solution.

However, I've added it to the README for clarification: #81
